version: "3.9"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes: [mongo_data:/data/db]
  redis:
    image: redis:7
    restart: unless-stopped
  api:
    image: ghcr.io/OWNER/fm-api:latest # replace OWNER
    env_file: .env
    depends_on: [mongo, redis]
  web:
    image: ghcr.io/OWNER/fm-web:latest # replace OWNER
    depends_on: [api]
  proxy:
    image: nginx:1.27-alpine
    ports: ["80:80","443:443"]
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/ssl:ro
    depends_on: [web, api]
volumes:
  mongo_data:
